#!/bin/bash

[Unit]
Description="App Description"

[Service]
WorkingDirectory=/var/www/dotnet
ExecStart=/usr/bin/dotnet /var/www/dotnet/app.dll
Restart=always
# Restart service after 5 seconds if the dotnet service crashes:
RestartSec=5
User=root
Environment=ASPNETCORE_ENVIRONMENT=Production
Environment=ASPNETCORE_URLS=http://localhost:5001


[Install]
WantedBy=multi-user.target

